mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (ProductsDetailsView,
                    ProductListView,
                    OrderListView,
                    OrderDetailView,
                    ProductCreateView,
                    OrderCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    OrderUpdateView,
                    OrderDeleteView,
                    OrdersDataExportView,
                    HelloView,
                    ProductViewSet,
                    OrderViewSet,
                    LastProductsFeed,
                    )


router = DefaultRouter()
router.register('products', ProductViewSet)
router.register('orders', OrderViewSet)


app_name = 'shopapp'
urlpatterns = [
    path("products/", ProductListView.as_view(), name='products_list'),
    path("products/create/", ProductCreateView.as_view(), name='product_create'),
    path("products/<int:pk>/", ProductsDetailsView.as_view(), name='products_details'),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name='products_update'),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name='products_delete'),
    path("products/latest/feed/", LastProductsFeed(), name='products_latest_feed'),
    path("orders/", OrderListView.as_view(), name='order_list'),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name='orders_detail'),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name='orders_update'),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name='orders_delete'),
    path("orders/create/", OrderCreateView.as_view(), name='order_create'),
    path("orders/export/", OrdersDataExportView.as_view(), name='orders_export'),
    path('hello/', HelloView.as_view(), name='hello'),
    path('api', include(router.urls))

]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _, gettext as __


def product_preview_image_path(instance: 'Product', filename: str) -> str:
    return 'products/product_{pk}/preview_{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель товаров которые можно заказать или положить в корзину
    Заказы тут: :model: `shopapp.Order`
    """
    class Meta:
        ordering = ['name', 'price']
        verbose_name = _('product')
        verbose_name_plural = _('products')

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='created_product',
        null=True,
        blank=False,
        editable=False
    )
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_image_path)

    def __str__(self):
        return __(self.name)

    def get_absolute_url(self):
        return reverse('shopapp:product-detail', kwargs={'pk': self.pk})


def product_image_path(instance: 'ProductImage', filename: str) -> str:
    return 'products/product_{pk}/preview_{filename}'.format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_image_path)
    short_description = models.CharField(max_length=255, null=False, blank=True)


class Order(models.Model):
    class Meta:
        verbose_name = _('order')
        verbose_name_plural = _("orders")


    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    receipt = models.FileField(null=True, blank=True, upload_to='orders/receipts/')

    def __str__(self):
        return __(self.delivery_address)

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Create
        </button>
    </form>
    
    </div>
    <div>
    <a href="{% url 'shopapp:orders_list' %}">
        Back to orders list
    </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Create
        </button>
    </form>
    
    </div>
    <div>
    <a href="{% url 'shopapp:products_list' %}">
        Back to products list
    </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
    {% if not groups %}
        <h3> No groups yet </h3>
    {% else %}
        <ul>
            {% for group in groups %}
            <li>
                <div>{{ group.name }}</div>
                <ul>
                    {% for permission in group.permissions.all %}
                        <li>
                            {{ permission.name }}
                            (<code>{{ permission.codename }}</code>)
                        </li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items%}
{% load admin_urls %}
    <li>
        <a href='{% url 'admin:import_orders_csv' %}' class="addlink">
            ImportCSV
        </a>
    </li>
    {{ block.super }}
{% endblock  %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete {{ object.name }}?</h1>
    <br>
    <div>
    <a href="{% url 'shopapp:orders_detail' pk=object.pk %}">
        Back to order # {{ object.pk }}
    </a>
    </div>
    <br>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Delete
        </button>
    </form>
    </div>
    
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Order #{{ object.pk }}</h1>
    <div>
       <p>Order by: {% firstof object.name.first_name object.user.username %}</p>
       <p>Promocode: <code> {{ object.promocode }}</code></p>
       <p>Delivery adress: {{ object.delivery_address }}</p>
        
       <div>
           Product in order:
           <ul>
               {% for product in object.products.all %}
                   <li> {{ product.name }} for ${{ product.price }}</li>
               {% endfor %}
           </ul>
       </div>
   </div>
    <div>
    <a href="{% url 'shopapp:orders_update' pk=object.pk %}">
        Update order # {{ object.pk }}
    </a>
    </div>
    <div>
    <a href="{% url 'shopapp:orders_delete' pk=object.pk %}">
        Delete order # {{ object.pk }}
    </a>
    </div>
    <div>
    <a href="{% url 'shopapp:order_list' %}">
        Back to products list
    </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Create
        </button>
    </form>
    
    </div>
    <div>
    <a href="{% url 'shopapp:order_list' %}">
        Back to orders list
    </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
       <div>
       {% for order in object_list %}
           <div>
                <p><a href="{% url 'shopapp:orders_detail' pk=order.pk %}">Detail for order # {{ order.pk }}</a> </p>
               <p>Order by: {% firstof order.name.first_name order.user.username %}</p>
               <p>Promocode: <code> {{ order.promocode }}</code></p>
               <p>Delivery adress: {{ order.delivery_address }}</p>
                
               <div>
                   Product in order:
                   <ul>
                       {% for product in order.products.all %}
                           <li> {{ product.name }} for ${{ product.price }}</li>
                       {% endfor %}
                   </ul>
               </div>
           </div>
       {% endfor %}
       </div>
    {% else %}
       <h3> No orders yet </h3>
    {% endif %}
    <div>
    <a href="{% url 'shopapp:order_create' %}">
        Create order
    </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update order
{% endblock %}

{% block body %}
    <h1>Update rhe current order</h1>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Update
        </button>
    </form>
    
    </div>
    <div>
    <a href="{% url 'shopapp:orders_detail' pk=object.pk %}">
        Back to order # {{ object.pk }}
    </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items%}
{% load admin_urls %}
    <li>
        <a href='{% url 'admin:import_products_csv' %}' class="addlink">
            ImportCSV
        </a>
    </li>
    {{ block.super }}
{% endblock  %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div>
    <a href="{% url 'shopapp:products_details' pk=object.pk %}">
        Back to product # {{ object.pk }}
    </a>
    </div>
    <br>
    <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Archive
        </button>
    </form>
    </div>
    
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Create
        </button>
    </form>
    
    </div>
    <div>
    <a href="{% url 'shopapp:products_list' %}">
        Back to products list
    </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>
        <div>Created by: {{ product.created_by }}</div>
        {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
    </div>
    <div>
        <h3>Images</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src={{ img.image.url }} alt={{ img.image.name }}>
                </div>
                <div> Description: {{ img.description }}</div>                
            {% empty %}
                <p>No images uploaded yet</p>
            {% endfor %}
            
        </div>
    </div>
    {%  if perms.shopapp.change_product  and product.created_by == user or user.is_superuser %}
        <div>
            <a href="{% url 'shopapp:products_update' pk=product.pk %}">Update product</a>
        </div>
        <div>
            <a href="{% url 'shopapp:products_delete' pk=product.pk %}">Archive product</a>
        </div>
    {% else %}
        <p>You have no permissions to update and delete product</p>
    {% endif %}
    <div>
    <a href="{% url 'shopapp:products_list' %}">
        Back to products list
    </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products:' %}</h1>
    {% if products %}
        <div>
        {% blocktranslate count counter=products|length %}
            There is only one product on this page
            {% plural %}
            There are {{counter}} products on this page
        {% endblocktranslate %}
        </div>
        
       <div>
       {% for product in products %}
           <div>
               {% url 'shopapp:products_details' pk=product.pk as details_url%}
               <p><a href="{{details_url}}"> {% translate 'Name' context 'product_name' %}: {{ product.name }} </a></p>
               <p>{% translate 'Price' %}: {{ product.price }}</p>
                {% translate 'no discount' as no_discount %}
               <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}           
           </div>
       {% endfor %}
       </div>
    
    {% else %}
       <h3> {% translate 'No products  yet' %}  </h3>
    {% endif %}
    
    <div>
    {% if perms.shopapp.create_product %}
        <a href="{% url 'shopapp:product_create' %}">
           {% translate 'Create a new product' %} 
        </a>
    {% else %}
        <p>{% translate 'You have no permissions to create product' %}</p>
    {% endif %}
    </div>
{% endblock %}