mysite/myauth/urls.py
import profile

from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from shopapp.views import HelloView
from .views import *



app_name = 'myauth'
urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True
         ),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about_me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('user/<int:pk>/update', ProfileUpdateView.as_view(), name='update_profile'),
    path('users/', UsersView.as_view(), name='users'),
    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='user_orders'),
    path('user/<int:pk>', AboutUserView.as_view(), name='about_user'),
    path('users/<int:user_id>/orders/export/', UserOrdersExportView.as_view(), name='user_orders_export'),
]

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def user_avatar_path(instance: 'Profile', filename: str) -> str:
    return 'avatars/user_{pk}/{filename}'.format(
        pk=instance.username.pk,
        filename=filename,
    )


class Profile(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=user_avatar_path)

mysite/myauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from myauth.models import Profile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='Email')
    avatar = forms.ImageField(label='Avatar')
    bio = forms.CharField(label='Bio')

    class Meta:
        model = User
        fields = ('username', 'email', 'avatar', 'bio')


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('avatar', 'bio')


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email', 'last_name', 'first_name')

    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField(label='Last Name')
    avatar = forms.ImageField(label='Avatar')
    bio = forms.CharField(label='Bio')

mysite/myauth/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.cache import cache
from django.db.models import Prefetch
from rest_framework.generics import get_object_or_404, GenericAPIView
from rest_framework.response import Response
from rest_framework.views import APIView
from shopapp.models import Order, Product
from .forms import *
from .models import Profile
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView
from .serializers import OrderSerializer


class UsersView(ListView):
    queryset = User.objects.all()
    template_name = 'myauth/users.html'


class AboutMeView(TemplateView):
    template_name = 'myauth/about-me.html'


class AboutUserView(DetailView):
    queryset = User.objects.prefetch_related('profile')
    template_name = 'myauth/about_user.html'


class RegisterView(CreateView):
    form_class = RegistrationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about_me')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        avatar = form.cleaned_data.get('avatar')
        bio = form.cleaned_data.get('bio')
        Profile.objects.create(username=self.object, avatar=avatar, bio=bio)
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class ProfileUpdateView(UpdateView):
    model = User
    queryset = User.objects.prefetch_related('profile')
    template_name = 'myauth/update.html'
    form_class = UserUpdateForm

    def get_initial(self):
        initial = super().get_initial()
        print(initial)
        initial['bio'] = self.object.profile.bio
        initial['avatar'] = self.object.profile.avatar
        print(initial)
        return initial

    def form_valid(self, form):
        response = super().form_valid(form)
        avatar = form.cleaned_data.get('avatar')
        bio = form.cleaned_data.get('bio')
        Profile.objects.filter(username=self.object.pk).update(bio=bio)
        obj = Profile.objects.get(username=self.object.pk)
        obj.avatar = avatar
        obj.save()
        return response

    def get_success_url(self):
        return reverse_lazy('myauth:about_user', kwargs={'pk': self.object.pk})

    def get_form_class(self):
        if self.request.user.is_staff or self.request.user.pk == self.object.pk:
            return UserUpdateForm
        else:
            raise PermissionDenied


class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = 'myauth/order_list.html'

    def get_queryset(self):
        self.owner = User.objects.get(pk=self.kwargs['user_id'])
        return Order.objects.filter(user=self.owner).prefetch_related('products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner'] = self.owner
        return context


class Logout(LogoutView):
    next_page = reverse_lazy('myauth:login')


class UserOrdersExportView(APIView):
    def get(self, request, user_id):
        cache_key = f'user_{user_id}_orders'
        orders = cache.get(cache_key)
        if orders is None:
            user = get_object_or_404(User, pk=user_id)
            orders = Order.objects.filter(user=user).order_by('id').prefetch_related(Prefetch('products', queryset=Product.objects.only('id')))
            cache.set(cache_key, orders, timeout=20)
        serializer = OrderSerializer(orders, many=True)
        return Response(serializer.data)
    

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}


{% block title %}
    About me
{% endblock title %}

{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
        <h2>Detail</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Lastname: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
        <div>
            {% if user.profile.avatar %}
                <a href={% url 'myauth:update_profile' pk=user.pk %}>
                    <img style="width: 300px; height: auto" src='{{ user.profile.avatar.url }}' alt="{{ user.profile.avatar.name }}">
                </a>
                <p>Фото профиля. Нажмите на картинку, чтобы изменить</p>
            {% else %} 
                <p>No avatar for <strong>{{ user.username }}</strong> yet</p>                            
            {% endif %}
        </div>
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock body %}

mysite/myauth/templates/myauth/about_user.html
{% extends 'myauth/base.html' %}


{% block title %}
    About me
{% endblock title %}

{% block body %}
    <h1>User info</h1>
    {% if request.user.is_authenticated %}
        <h2>Detail</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Lastname: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
        <div>
            {% if user.profile.avatar %}
                    <img style="width: 300px; height: auto" src='{{ user.profile.avatar.url }}' alt="{{ user.profile.avatar.name }}">
            {% else %} 

                    <p>No avatar for <strong>{{ user.username }}</strong> yet</p>                 
            {% endif %}
            {% if request.user.is_staff %}
                <a href={% url 'myauth:update_profile' pk=user.pk%}><strong>Редактировать {{ user.username }}</strong></a>
            {% elif request.user.pk == user.pk %}
                <a href={% url 'myauth:update_profile' pk=user.pk%}><strong>Редактировать {{ user.username }}</strong></a>
            {% else %}
                <p>You have no permissions to update this profile</p>
            {% endif %}
        </div>
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock body %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base title
        {% endblock %}
    </title>
    <style>
        body {
            background-color: lightblue;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        h1 {
            color: darkblue;
        }
        .login{
            height: 300px;
            width: 400px;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        
        header {
            display: flex;
            flex-direction: row;
            margin: 3px;
        }
         
        header div{
            margin: 3px;
        }
        
    </style>
</head>
<body>
<header>
{% if request.user.is_authenticated %}
<div>
    <form action="{% url "myauth:logout" %}" method="POST">
        {% csrf_token %}
        <button class='btn btn-danger' type="submit">Log out</button>
    </form>
</div>
<div>
    <a href={% url 'myauth:update_profile' pk=request.user.pk%}>
        <button class='btn btn-warning'>Update my profile</button> 
    </a>
</div>
    
        <p>Hi, {{ request.user.username }}</p>
{% endif %}
</header>

{% block body %}

Base body
{% endblock %}

</body>

</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Авторизация
{% endblock %}

{% block body %}
    <h1>Авторизация</h1>
    <div class="login">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit"  class="btn btn-success">Войти</button>
        </form>
        
    </div>
    

    
{% endblock %}

mysite/myauth/templates/myauth/order_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
            {% cache 60 user_orders owner.pk %}
                <h3> У пользователя {{ owner }} следующие  заказы: </h3>
                {% for order in object_list %}
                    <div>
                        <p><a href="{% url 'shopapp:orders_detail' pk=order.pk %}">Detail for order # {{ order.pk }}</a></p>
                        <p>Promocode: <code> {{ order.promocode }}</code></p>
                        <p>Delivery adress: {{ order.delivery_address }}</p>
    
                        <div>
                            Product in order:
                            <ul>
                                {% for product in order.products.all %}
                                    <li> {{ product.name }} for ${{ product.price }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div>
                        {% lorem 1p random %}
                    </div>
            {% endfor %}
            {% endcache %}
        </div>
    {% else %}
        <h3> У пользователя {{ owner }} </h3>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Create order
        </a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}


{% block title %}
    Register
{% endblock title %}

{% block body %}
    <h1>Register</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Register</button>
    </form>
{% endblock body %}

mysite/myauth/templates/myauth/update.html
{% extends 'myauth/base.html' %}


{% block title %}
    Update
{% endblock title %}

{% block body %}
    <h1>Update</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Update</button>
    </form>
    <div>
        {% if user.profile.avatar %}
            <img style="width: 300px; height: auto" src='{{ user.profile.avatar.url }}' alt='{{ user.profile.avatar.name }}'>
            <p>Фото профиля.</p>
        {% else %} 
            <p>No avatar for <strong>{{ user.username }}</strong> yet</p>                            
        {% endif %}
    </div>
        
{% endblock body %}

mysite/myauth/templates/myauth/users.html
{% extends 'myauth/base.html' %}


{% block title %}
    Users
{% endblock title %}

{% block body %}
    <h1>Users info</h1>
    {% if user.is_authenticated %}
        {% for user_profile in object_list %}
            <p>Username: {{ user_profile.username }}</p>
            <p>First name: {{ user_profile.first_name }}</p>
            <p>Lastname: {{ user_profile.last_name }}</p>
            <p>Email: {{ user_profile.email }}</p>
            <a href={% url 'myauth:about_user' pk=user_profile.pk %}>See profile</a>
            <div>
                {% if user_profile.profile.avatar %}
                    <img style="width: 300px; height: auto" src='{{ user_profile.profile.avatar.url }}' alt='{{ user_profile.profile.avatar.name }}'>
                    <p>Фото профиля.</p>
                {% else %} 
                    <p>No avatar for <strong>{{ user_profile.username }}</strong> yet</p>                            
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <h2>User is anonymous. You cannot see profiles.</h2>
    {% endif %}
{% endblock body %}